spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sustc  # change this to your own jdbc url
    username: zhuozhuo  # change this to your own username (avoid using a superuser)
    password: wangzhuo123  # change this to your own password

logging:
  level:
    root: off
    io.sustc: debug

---

benchmark:
  data-path: data
  student-mode: true
